// Copyright 2016 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/widgets.dart';

import 'armadillo_drag_target.dart' show ArmadilloLongPressDraggable;

/// Used with [ArmadilloLongPressDraggable]s to display their drag feedback
/// widgets.
class ArmadilloOverlay extends StatefulWidget {
  /// Constructor.
  ArmadilloOverlay({Key key}) : super(key: key);

  @override
  ArmadilloOverlayState createState() => new ArmadilloOverlayState();
}

/// The [State] for [ArmadilloOverlay].  It tracks a set of builders which
/// [Widget]s generated by [ArmadilloLongPressDraggable]s.
class ArmadilloOverlayState extends State<ArmadilloOverlay> {
  final Set<WidgetBuilder> _builders = new Set<WidgetBuilder>();

  /// Returns true if it is displaying children.
  bool get hasBuilders => _builders.isNotEmpty;

  /// Adds a builder which will build a child [Widget] for this overlay.
  void addBuilder(WidgetBuilder builder) => setState(() {
        _builders.add(builder);
      });

  /// Removes a builder from being a child [Widget] for this overlay.
  void removeBuilder(WidgetBuilder builder) => setState(() {
        _builders.remove(builder);
      });

  @override
  Widget build(BuildContext context) => new Stack(
        fit: StackFit.passthrough,
        children: _builders
            .map(
              (WidgetBuilder builder) => builder(context),
            )
            .toList(),
      );
}
