# Copyright 2016 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

FUCHSIA_DIR ?= $(shell jiri -show-root)

SCRIPTS_DIR := $(realpath $(FUCHSIA_DIR)/topaz/tools/scripts)
COMMON_MAKEFILE := $(realpath $(SCRIPTS_DIR)/Makefile)

include $(COMMON_MAKEFILE)
